# Generated by Django 2.2.5 on 2019-12-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст цитаты')),
                ('author', models.CharField(max_length=128, verbose_name='Автор')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта автора')),
                ('status', models.CharField(blank=True, choices=[('new', 'Новая'), ('verified', 'Проверен')], default='new', max_length=128, verbose_name='Статус')),
                ('rating', models.IntegerField(blank=True, default=0, verbose_name='Рейтинг')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
